// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snippets.proto

package snippets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message
type SnippetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sleep                int32    `protobuf:"varint,2,opt,name=sleep,proto3" json:"sleep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnippetRequest) Reset()         { *m = SnippetRequest{} }
func (m *SnippetRequest) String() string { return proto.CompactTextString(m) }
func (*SnippetRequest) ProtoMessage()    {}
func (*SnippetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snippets_a1c27bbc90beee96, []int{0}
}
func (m *SnippetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnippetRequest.Unmarshal(m, b)
}
func (m *SnippetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnippetRequest.Marshal(b, m, deterministic)
}
func (dst *SnippetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnippetRequest.Merge(dst, src)
}
func (m *SnippetRequest) XXX_Size() int {
	return xxx_messageInfo_SnippetRequest.Size(m)
}
func (m *SnippetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnippetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnippetRequest proto.InternalMessageInfo

func (m *SnippetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SnippetRequest) GetSleep() int32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

// The response message.
type SnippetResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnippetResponse) Reset()         { *m = SnippetResponse{} }
func (m *SnippetResponse) String() string { return proto.CompactTextString(m) }
func (*SnippetResponse) ProtoMessage()    {}
func (*SnippetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snippets_a1c27bbc90beee96, []int{1}
}
func (m *SnippetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnippetResponse.Unmarshal(m, b)
}
func (m *SnippetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnippetResponse.Marshal(b, m, deterministic)
}
func (dst *SnippetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnippetResponse.Merge(dst, src)
}
func (m *SnippetResponse) XXX_Size() int {
	return xxx_messageInfo_SnippetResponse.Size(m)
}
func (m *SnippetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnippetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnippetResponse proto.InternalMessageInfo

func (m *SnippetResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SnippetRequest)(nil), "snippets.SnippetRequest")
	proto.RegisterType((*SnippetResponse)(nil), "snippets.SnippetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnippetsClient is the client API for Snippets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnippetsClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *SnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
}

type snippetsClient struct {
	cc *grpc.ClientConn
}

func NewSnippetsClient(cc *grpc.ClientConn) SnippetsClient {
	return &snippetsClient{cc}
}

func (c *snippetsClient) SayHello(ctx context.Context, in *SnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, "/snippets.Snippets/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnippetsServer is the server API for Snippets service.
type SnippetsServer interface {
	// Sends a greeting
	SayHello(context.Context, *SnippetRequest) (*SnippetResponse, error)
}

func RegisterSnippetsServer(s *grpc.Server, srv SnippetsServer) {
	s.RegisterService(&_Snippets_serviceDesc, srv)
}

func _Snippets_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snippets.Snippets/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetsServer).SayHello(ctx, req.(*SnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snippets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snippets.Snippets",
	HandlerType: (*SnippetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Snippets_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snippets.proto",
}

func init() { proto.RegisterFile("snippets.proto", fileDescriptor_snippets_a1c27bbc90beee96) }

var fileDescriptor_snippets_a1c27bbc90beee96 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xce, 0xcb, 0x2c,
	0x28, 0x48, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xac,
	0xb8, 0xf8, 0x82, 0x21, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b,
	0xb5, 0x38, 0x27, 0x35, 0xb5, 0x40, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc2, 0x51, 0xd2,
	0xe6, 0xe2, 0x87, 0xeb, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe0, 0x62, 0xcf, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x87, 0xe9, 0x87, 0x71, 0x8d, 0x7c, 0xb9, 0x38, 0xa0, 0x8a, 0x8b, 0x85,
	0x1c, 0xb9, 0x38, 0x82, 0x13, 0x2b, 0x3d, 0x52, 0x73, 0x72, 0xf2, 0x85, 0x24, 0xf4, 0xe0, 0x6e,
	0x43, 0x75, 0x88, 0x94, 0x24, 0x16, 0x19, 0x88, 0x35, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x8f, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x22, 0xd4, 0x11, 0x78, 0xda, 0x00, 0x00, 0x00,
}
